server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/olxdjavadb
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true