server:
  jwt:
    secret: "secret"
    issuer: "AnimalWorld"
    accessExpTime: "28800000"
    refreshExpTime: "31104000000"
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never

recaptcha:
  secret: "6LfhziwjAAAAANqzXgdzF94KhriJZPnJsWk2VJst"

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/web_uz?jdbcCompliantTruncation=false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.mailtrap.io
    port: 587
    username: b3fdbd14304b7d
    password: e2f7103234f93e

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth:
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
